name: CMake (Windows ARM32/64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-woa
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  build-32:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: dockcross/windows-armv7
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/mingw32-armv7.cmake

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build-woa32-${{env.BUILD_TYPE}}
          path: build/patcher.exe

  build-64:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: dockcross/windows-arm64
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/mingw32-aarch64.cmake

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build-woa64-${{env.BUILD_TYPE}}
          path: build/patcher.exe
